swipe:
  3: 
    left: 
      command: 'xdotool key Alt_L+Tab'
    right: 
      command: 'xdotool key Shift_L+Alt_L+Tab'
    up: 
      command: 'xdotool key Control_L+F10'
      threshold: 0.75
    down: 
      command: 'xdotool key Control_L+F12'
      threshold: 0.75
  4:
    up: 
      command: 'xdotool key Alt_LL+Left'
    down: 
      command: 'xdotool key Alt_L+Right'
    right: 
      command: 'xdotool key Control_L+Tab'
    left: 
      command: 'xdotool key Control_L+Shift_L+Tab'
pinch:
  2:
    in:
      command: 'xdotool key Control_L+plus'
      threshold: 0.1
    out:
      command: 'xdotool key Control_L+minus'
      threshold: 0.1

threshold:
  swipe: 0.75
  pinch: 0.75

interval:
  swipe: 1
  pinch: 1
